src/app.py
from factory import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=3000, use_reloader=True, extra_files=['./blueprints/data/settings.yaml'])

src/blueprints/cms.py
from flask import Blueprint ,render_template, redirect, request, url_for, flash
from werkzeug.utils import secure_filename
import os

from pyowm import OWM
from blueprints.data.api import OWM_API_KEY

from blueprints.data.settings import BACKGROUND, LOCATION
ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png'}
UPLOAD_FOLDER = './static/images/backgrounds'

cms_bp = Blueprint("cms", __name__)

owm = OWM(OWM_API_KEY)
mgr = owm.weather_manager()

@cms_bp.route("/settings", methods=["GET"])
def settings():
    weather = mgr.weather_at_place(LOCATION).weather.detailed_status
    temp = mgr.weather_at_place(LOCATION).weather.temperature('celsius')['temp']
    weather_symbol = mgr.weather_at_place(LOCATION).weather.weather_icon_name
    
    file = open('blueprints/data/settings.yaml', 'r')
    settings = file.read()
    file.seek(0)
    lines = len(file.readlines())
    file.close()

    print(lines)
    
    return render_template("settings.html", title="Settings", background=BACKGROUND, weather=weather, temp=temp, weather_symbol=weather_symbol, location=LOCATION, settings=settings, lines=lines)

@cms_bp.route("/cms/add/site", methods=["POST"])
def add_site():
    print(request.form)
    title = request.form["title"]
    url = request.form["url"]
    description = request.form["description"]
    icon = request.form["icon"]
    category = request.form["category"]

    text = f"""  - name: { title }
    url: { url }
    description: { description }
    icon: { icon }
    category: { category }"""

    with open('blueprints/data/settings.yaml', 'a') as file:
        file.write(text)

    return redirect(url_for("dash.dash"))

@cms_bp.route("/cms/edit", methods=["POST"])
def edit():
    print(request.form)

    text = request.form["settings"]
    text.strip("\r")
    print(text)

    with open('blueprints/data/settings.yaml', 'w') as file:
        file.write(text)

    return redirect(url_for("cms.settings"))

def allowed_file(filename):
    return '.' in filename and \
            filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@cms_bp.route("/cms/background", methods=["POST"])
def background():
    print(request.files)

    if 'file' in request.files:
        flash('No file part')
        return redirect(request.url)

    file = request.files['background']

    if file.filename == '':
        flash('No selected file')
        return redirect(request.url)

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        return redirect(url_for("cms.settings"))

    return redirect(url_for("cms.settings"))

src/blueprints/dashboard.py
from flask import Blueprint, render_template

from pyowm import OWM
from blueprints.data.api import OWM_API_KEY
from blueprints.data.settings import CATEGORIES, BACKGROUND, SITES, LOCATION

dash_bp = Blueprint('dash', __name__)

owm = OWM(OWM_API_KEY)
mgr = owm.weather_manager()

@dash_bp.route("/", methods=["GET"])
def dash():
    weather = mgr.weather_at_place(LOCATION).weather.detailed_status
    temp = mgr.weather_at_place(LOCATION).weather.temperature('celsius')['temp']
    weather_symbol = mgr.weather_at_place(LOCATION).weather.weather_icon_name

    return render_template("dashboard.html", title="Dashboard", background=BACKGROUND, weather=weather, temp=temp, weather_symbol=weather_symbol, location=LOCATION, sites=SITES, categories=CATEGORIES)

src/templates/dashboard.html
{% extends "index.html" %}

{% block content %}
<head>
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
</head>

    {% for category in categories %}
    <div class="category {{ category }}">
        <header class="card">
            {{ category }}
        </header>
        <div class="links">
        {% for site in sites %}
        {% if site.category == category %}
            <a class="site card link" href="{{ site.url }}" target="_blank" title="{{ site.description }}">
                <img src="{{ site.img }}" alt="{{ site.name }}">
                {{ site.name }}
            </a>
        {% endif %}
        {% endfor %}
        </div>
    </div>
    {% endfor %}
    <button id="modalButton" class="card link">Add site</button>
    <a class="card link" href="{{ url_for('cms.settings') }}">Edit settings</a>
    <div class="card modal" id="modal">
        <div class="modal-title">
            <h1>Add Site</h1>
            <div class="close" id="close">X</div>
        </div>
        <form class="modal-form form" action="{{ url_for('cms.add_site') }}" id="siteform" method="POST">
            <label for="title">Title</label>
            <input class="form-entry" type="text" name="title" required placeholder="Link title...">

            <label for="url">URL</label>
            <input class="form-entry" type="url" name="url" required placeholder="Link url...">

            <label for="description">Description</label>
            <input class="form-entry" type="text" name="description" placeholder="Link description...">

            <label for="icon">Icon</label>
            <input class="form-entry" type="text" name="icon" required placeholder="Link icon...">

            <label for="category">Category</label>
            <select class="form-entry" name="category" id="category" form="siteform">
                {% for category in categories %}
                <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>

            <input class="submit" type="submit" value="Add">
        </form>
    </div>
{% endblock %}

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ title }}</title>
        <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
        <link rel="icon" type="image/png" href="#"> <!-- Add link when logo is made -->

        <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.min.js"></script>-->
    </head>
    <body style="background-image: url('{{ background }}');">
        <div class="sidebar">
            <div class="datetime card">
                <div class="time">time</div>
                <div class="date">date</div>
            </div>
            <div class="weather card">
                <h1>{{ weather }}</h1>
                <div class="weather-info">
                    <img class="weather-symbol" src="/static/images/weather-icons/{{ weather_symbol }}.svg">
                    <div class="weather-status">
                        <span>{{ temp }}°C</span>
                        {{ location }}
                    </div>
                </div>
            </div>
            <div class="stats card">
                Coming soon :)
            </div>
            <div class="drive card">
                Coming soon :)
            </div>
            <div class="mady-by card">
                HomeLabHub, made with &hearts; by <a href="https://github.com/hardomx" target="_blank">HardoMX</a>
            </div>
        </div>
        <div class="content">
            <main>
            {% block content %}
                Something went wrong :(
            {% endblock %}
            </main>
        </div>
    </body>
    <script src="{{ url_for('static', filename='js/time.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modal.js') }}"></script>
</html>

src/templates/settings.html
{% extends "index.html" %}

{% block content %}
    <head>
        <link href="{{ url_for('static', filename='css/settings.css') }}" rel="stylesheet">
    </head>
    <header>
        <h1 class="card">Settings</h1>
    </header>
    <form action="{{ url_for('cms.edit') }}" method="POST" class="settings-form form card">
        <label for="settings">Edit settings file</label>
        <textarea name="settings" id="settings" rows="{{ lines }}" spellcheck="false">{{ settings }}</textarea>
        <input type="submit" value="Save">
    </form>
    <form action="{{ url_for('cms.background') }}" method="POST" enctype="multipart/form-data" class="background-form form card">
        <label for="background">Upload background</label>
        <input class="" type="file" name="background" accept="image/*" required>
        <input type="submit" value="Upload">
    </form>
    <a class="return card" href="/">Return to dashboard</a>
{% endblock %}